title: Donovan Bell's Projects
email: donovanbell@proton.me
description: >- 
  A showcase of Donovan's amazing projects.
baseurl: "" 
url: "https://dotdon.github.io"
theme: minima
markdown: kramdown
highlighter: rouge
collections:
  projects:
    output: true
