title: Dot Don's Projects
email: your-email@example.com
description: >- 
  A showcase of Dot Don's amazing projects.
baseurl: "" 
url: "https://dotdon.github.io"
theme: minima
markdown: kramdown
highlighter: rouge
collections:
  projects:
    output: true
